In [1]:
import numpy as np

In [2]:
arr =np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [3]:
a=[5,4]
a

[5, 4]

In [4]:
np.array(a)

array([5, 4])

In [5]:
b=[[5,4,3],[3,4,4],[4,56,4]]
b

[[5, 4, 3], [3, 4, 4], [4, 56, 4]]

In [6]:
np.array(b)

array([[ 5,  4,  3],
       [ 3,  4,  4],
       [ 4, 56,  4]])

In [10]:
z=np.ones((4,7))
z

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [12]:
arr= np.linspace(0,1,100)
arr

array([0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
       0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909,
       0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
       0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919,
       0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
       0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929,
       0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
       0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939,
       0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
       0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949,
       0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
       0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ,
       0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
       0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ,
       0.70707071, 0.71717172, 0.72727273, 0.73737374, 0.74747

In [13]:
np.random.rand(852)

array([0.59259995, 0.51685083, 0.34575152, 0.42866535, 0.52031019,
       0.4861513 , 0.37987114, 0.62075766, 0.86980268, 0.77843942,
       0.04564781, 0.49615422, 0.49294838, 0.56872321, 0.39254524,
       0.23424818, 0.64146075, 0.55454784, 0.13837775, 0.29489589,
       0.01848508, 0.00316991, 0.9771889 , 0.26098167, 0.02278527,
       0.87464624, 0.44068559, 0.41813713, 0.10049538, 0.49020615,
       0.04060819, 0.80245626, 0.14205525, 0.80968987, 0.46177852,
       0.81915882, 0.53157474, 0.74436673, 0.53282257, 0.09083144,
       0.9632833 , 0.00751237, 0.89720962, 0.83055989, 0.37756743,
       0.31115612, 0.87697932, 0.17099775, 0.59288093, 0.13360858,
       0.22502971, 0.24580076, 0.72923909, 0.84685145, 0.95899905,
       0.56763966, 0.364431  , 0.79602089, 0.39646706, 0.65668468,
       0.81447629, 0.08261436, 0.7872836 , 0.40008916, 0.68728116,
       0.10024631, 0.71634372, 0.88122345, 0.21832119, 0.80546406,
       0.22385197, 0.80727192, 0.83824419, 0.25126941, 0.83157

In [23]:
arr = np.arange(1,51).reshape(5,10)
arr

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50]])

In [25]:
np.random.rand(10).reshape(2,5)

array([[0.92686897, 0.42726571, 0.85280664, 0.80580874, 0.18728688],
       [0.44573297, 0.48689799, 0.08303635, 0.98362811, 0.30096359]])

In [14]:
arr.dtype

dtype('float64')

In [15]:
arr.min()

np.float64(0.0)

In [16]:
arr.max()

np.float64(1.0)

In [17]:
arr.sum()

np.float64(50.0)

In [18]:
arr.shape

(100,)

In [19]:
arr.std()

np.float64(0.29157646512850627)

In [20]:
arr =np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [27]:
arr_slice=arr[3::2]
arr_slice
arr

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50]])

In [31]:
arr = np.random.rand(90)
arr

array([0.38848096, 0.12365075, 0.09908792, 0.03581328, 0.01224132,
       0.62936125, 0.88818341, 0.66577919, 0.33345961, 0.81802198,
       0.91506802, 0.80167277, 0.01583215, 0.85772679, 0.28595325,
       0.97641911, 0.82862561, 0.75653597, 0.95220397, 0.72833905,
       0.71188284, 0.52486809, 0.40918413, 0.74517471, 0.761111  ,
       0.40262149, 0.50207037, 0.82069221, 0.75654271, 0.27212045,
       0.37399773, 0.32647925, 0.77639934, 0.4289209 , 0.55726717,
       0.21517752, 0.22448739, 0.46819409, 0.18562868, 0.35027718,
       0.4511112 , 0.01714271, 0.34379629, 0.34539829, 0.97067144,
       0.80076672, 0.81760959, 0.42250712, 0.26400521, 0.87268247,
       0.1173903 , 0.77695937, 0.57109574, 0.77148301, 0.53860534,
       0.15361367, 0.77840426, 0.33725202, 0.70071614, 0.94450729,
       0.65227634, 0.32951918, 0.62171513, 0.99078803, 0.59868414,
       0.67120362, 0.8132054 , 0.28298304, 0.44666715, 0.46512565,
       0.49667753, 0.14906059, 0.26251567, 0.55187214, 0.52155

In [34]:
bool_index = arr %2 == 0
bool_index

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False])

In [38]:
arr = np.arange(1, 51).reshape(5, 10)
odd_index = arr % 2 != 0
arr_odd = arr[odd_index]
arr_odd

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49])

In [46]:
a1 = np.array([1,2,3,4,5])
a2 = np.array([6,5,3,32])

In [48]:
arr +10

array([[11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50],
       [51, 52, 53, 54, 55, 56, 57, 58, 59, 60]])

In [49]:
a1 + np.pad(a2, (0, 1), constant_values=0)

array([ 7,  7,  6, 36,  5])

In [50]:
import pandas as pd

In [ ]:
labels =['a','b','c']
my_list=[10,20,30]
arr =np.array([41,3.4])
